//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercadosfera.Data
{
    using System;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class CategoryFilter
    {
        [DataMember]
        public int idCategoria { get; set; }

        [DataMember]
        public int Cantidad { get; set; }

        [DataMember]
        public string DescCategoria { get; set; }

        [DataMember]
        public Nullable<int> idSubcategoria { get; set; }

        [DataMember]
        public string DescSubcategoria { get; set; }
    }
}
