//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercadosfera.Data
{
    using System;
    using System.Collections.Generic;
     using System.Runtime.Serialization;
    [Serializable]
[DataContract] public partial class LOCALIDADES
    {
        public LOCALIDADES()
        {
            this.TIENDAS = new HashSet<TIENDAS>();
        }
    
        [DataMember] public int ID { get; set; }
        [DataMember] public Nullable<int> IdComunidad { get; set; }
        [DataMember] public string Descripcion { get; set; }
        [DataMember] public string Create_id { get; set; }
        [DataMember] public string Create_dt { get; set; }
        [DataMember] public string Update_id { get; set; }
        [DataMember] public string Update_dt { get; set; }
        [DataMember] public string Delete_id { get; set; }
        [DataMember] public string Delete_dt { get; set; }
        [DataMember] public string UrlOrchard { get; set; }
    
        [DataMember] public virtual COMUNIDADES COMUNIDADES { get; set; }
        [DataMember] public virtual ICollection<TIENDAS> TIENDAS { get; set; }
    }
}
