//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

            namespace Mercadosfera.Data
            {
                using System;
                using System.Runtime.Serialization;

                [DataContract]
                public partial class ProductoDetalle
                {
                    [DataMember]
                    public int ID { get; set; }

                    [DataMember]
                    public string Descripcion { get; set; }

                    [DataMember]
                    public string DescripcionCorta { get; set; }

                    [DataMember]
                    public string Titulo { get; set; }

                    [DataMember]
                    public Nullable<decimal> Precio { get; set; }

                    [DataMember]
                    public string Moneda { get; set; }

                    [DataMember]
                    public string DimensionesPaquete { get; set; }

                    [DataMember]
                    public string Conservacion { get; set; }

                    [DataMember]
                    public string Caducidad { get; set; }

                    [DataMember]
                    public Nullable<int> UnidadesPaquete { get; set; }

                    [DataMember]
                    public string Formato { get; set; }

                    [DataMember]
                    public Nullable<int> Peso { get; set; }

                    [DataMember]
                    public string TIPOPRODUCTO { get; set; }

                    [DataMember]
                    public Nullable<int> IdTienda { get; set; }

                    [DataMember]
                    public string UrlProducto { get; set; }
                }
            }
