//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercadosfera.Data
{
    using System;
    using System.Collections.Generic;
     using System.Runtime.Serialization;
    [Serializable]
[DataContract] public partial class PRODUCTOS
    {
        [DataMember] public int ID { get; set; }
        [DataMember] public Nullable<int> IdTienda { get; set; }
        [DataMember] public Nullable<int> IdTipoProducto { get; set; }
        [DataMember] public Nullable<int> Peso { get; set; }
        [DataMember] public Nullable<int> IdFormato { get; set; }
        [DataMember] public Nullable<int> UnidadesPaquete { get; set; }
        [DataMember] public string Caducidad { get; set; }
        [DataMember] public string Conservacion { get; set; }
        [DataMember] public Nullable<int> IdCertificadoCalidad { get; set; }
        [DataMember] public string DimensionesPaquete { get; set; }
        [DataMember] public Nullable<decimal> Precio { get; set; }
        [DataMember] public string Moneda { get; set; }
        [DataMember] public string Create_id { get; set; }
        [DataMember] public Nullable<System.DateTime> Create_dt { get; set; }
        [DataMember] public string Update_Id { get; set; }
        [DataMember] public Nullable<System.DateTime> Update_dt { get; set; }
        [DataMember] public string Delete_id { get; set; }
        [DataMember] public Nullable<System.DateTime> Delete_dt { get; set; }
        [DataMember] public string Descripcion { get; set; }
        [DataMember] public string DescripcionCorta { get; set; }
        [DataMember] public string Titulo { get; set; }
        [DataMember] public string UrlProducto { get; set; }
    
        [DataMember] public virtual CERTIFICADOS CERTIFICADOS { get; set; }
        [DataMember] public virtual FORMATOS FORMATOS { get; set; }
        [DataMember] public virtual TIPOPRODUCTO TIPOPRODUCTO { get; set; }
    }
}
