//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercadosfera.Data
{
    using System;
    using System.Collections.Generic;
     using System.Runtime.Serialization;
    [Serializable]
[DataContract] public partial class TIENDAS
    {
        public TIENDAS()
        {
            this.TIENDAS_TEXTOS = new HashSet<TIENDAS_TEXTOS>();
        }
    
        [DataMember] public int Id { get; set; }
        [DataMember] public Nullable<int> UsuarioOrchard { get; set; }
        [DataMember] public string Nombre { get; set; }
        [DataMember] public string Descripcion { get; set; }
        [DataMember] public string Direccion { get; set; }
        [DataMember] public string DNI { get; set; }
        [DataMember] public string Mail { get; set; }
        [DataMember] public string Create_id { get; set; }
        [DataMember] public Nullable<System.DateTime> Create_dt { get; set; }
        [DataMember] public string Update_Id { get; set; }
        [DataMember] public Nullable<System.DateTime> Update_dt { get; set; }
        [DataMember] public string Delete_id { get; set; }
        [DataMember] public Nullable<System.DateTime> Delete_dt { get; set; }
        [DataMember] public string Telefono { get; set; }
        [DataMember] public string Web { get; set; }
        [DataMember] public string Facebook { get; set; }
        [DataMember] public Nullable<int> IdGaleriaImagenes { get; set; }
        [DataMember] public string CoordenadasMaps { get; set; }
        [DataMember] public Nullable<int> IdComunidad { get; set; }
        [DataMember] public Nullable<int> IdLocalidad { get; set; }
        [DataMember] public string UrlOrchard { get; set; }
    
        [DataMember] public virtual LOCALIDADES LOCALIDADES { get; set; }
        [DataMember] public virtual ICollection<TIENDAS_TEXTOS> TIENDAS_TEXTOS { get; set; }
    }
}
